name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Apt
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev libpq-dev libudev-dev libmysqlclient-dev
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
#          target: wasm32-unknown-unknown
#    - name: Build WASM
#      uses: actions-rs/cargo@v1
#      with:
#        command: build
#        target: wasm32-unknown-unknown
#    - name: Install WASM-bindgen
#      uses: actions-rs/cargo@v1
#      with:
#        command: install
#        args: wasm-bindgen-cli
#    - name: Build ASM
#      uses: actions-rs/cargo@v1
#      with:
#        command: build
#        target: wasm32-unknown-unknown
#        args: -p puzzleverse-client
#    - name: Build WASM binding
#      run: wasm-bindgen --target web target/wasm32-unknown-unknown/debug/puzzleverse-client.wasm  --out-dir server/ --no-typescript
    - name: Build Native
      uses: actions-rs/cargo@v1
      with:
        command: build
